#!/bin/sh
# graph
# Draw graph

usage="graph cmd ...
where *cmd* is one of:
download
split
"

# URL of the file containing temperatures.
Turl="http://data.giss.nasa.gov/gistemp/tabledata_v3/GLB.Ts+dSST.txt"

download () {
    curl "$Turl" > data.txt
}

split () {
  (
    # The last complete year
    last="$(grep -E '^[0-9]{4}( *-?[0-9]+){12}' data.txt |
              cut -c 1-4 | tail -1)"
    for m in 1 2 3 4 5 6 7 8 9 10 11 12
    do
        p=$((5*$m+1))
        q=$(($p+4))
        awk '/^[0-9]/ && +$1 && $1 < '"$last"' {print $0, NR}' data.txt |
          cut "-c1-5,${p}-${q}" > "m${m}.txt"
    done
  )
}

svg () {
  (
    for m in 1 2 3 4 5 6 7 8 9 10 11 12
    do
        svgone "$m"
    done
  )
}

svgone () {
  # $1 is the month number
  (
    # Unit in SVG file is one tenth of a millimetre.
    # Number of units offset for y=0 point.
    # Values of input y go from about -90 to about +90
    # Normal is increasing temps up the page; if flipped then increasing
    # temps are down the page.
    # If the first year is >= 2000 then the x-axis will be flipped and
    # older years will be to the right.
    flipped="no"
    offset=500
    # Number of vertical units for one unit temperature.
    yscale=-5
    # Horizontal size of one year
    hstep=20
    base=1000
    if [ "$flipped" = "yes" ] ; then
        yscale=$((-$yscale))
        base=0
    fi
    m="$1"
    f="m${m}.txt"
    path=$(
        echo M0 "$base"
        while read row
        do
            set -- $row
            if [ -z "$hscale" ] && [ "$1" -ge 2000 ] ; then
                hscale=-"$hstep"
                fy="$1"
            else
                hscale="$hstep"
                fy="$1"
            fi
            y=$(($offset + $2*$yscale))
            x=$(( ($1-$fy)*$hscale ))
            echo "V${y}h${hstep}"
        done < "$f"
        echo V"$base" Z
        )
    range=$(sort -n "$f" | sed -n '1s/ .*//p;$s/ .*//p')
    range=$(echo $range | sed 's/ / to /')
    text="$range  $(Month $m)"
    path=$(echo $path)
    cat <<! > "s${m}.svg"
<svg
  xmlns="http://www.w3.org/2000/svg"
  >
<defs>
  <style type="text/css">
    path { stroke: red; stroke-width: 1.2; fill: none }
    text { fill: black; font-family: Verdana }
  </style>
</defs>


<g transform="scale(0.4)">
<path d="$path" />
<text x="1200" y="900" font-size="48">$text</text>
</g>
</svg>
!
  )
}

Month () {
    # Convert numeric month, 1 to 12, into full name.
    date -d "$1/20" +%B
}

for a
do
    $a
done
